import type { PartialMessageCatalog } from "@/features/i18n/i18n";

const es = {
  Reference: "Referencia", "Formula Library": "Biblioteca de fórmulas", "Start Formula Drill": "Practicar fórmulas",
  "Find consulting math formulas, examples, and direct links into related practice.": "Consulta fórmulas de matemáticas de consultoría, ejemplos y prácticas relacionadas.",
  "Find a Formula": "Buscar una fórmula", "Showing {visible} of {total} local formulas.": "Mostrando {visible} de {total} fórmulas locales.",
  "Clear Filters": "Borrar filtros", "Search formulas": "Buscar fórmulas", "Margin, breakeven, growth...": "Margen, equilibrio, crecimiento...",
  "Formula category": "Categoría de fórmula", "All formulas": "Todas las fórmulas", "Category: All formulas": "Categoría: todas", "Category: {category}": "Categoría: {category}",
  "Search: Any keyword": "Búsqueda: cualquier palabra", "Search: {search}": "Búsqueda: {search}", formula: "fórmula", formulas: "fórmulas",
  "No Results": "Sin resultados", "No formulas match the current filters.": "Ninguna fórmula coincide con los filtros.",
  "Clear the filters to return to all formulas, or start a drill if you already know what you want to practice.": "Borra los filtros para ver todas las fórmulas o inicia una práctica.",
  "Reset Formula Filters": "Restablecer filtros", "Start Drill": "Iniciar práctica", Formula: "Fórmula", "How to use it": "Cómo usarla", Example: "Ejemplo",
  "Practice this formula with a short built-in drill using related question templates.": "Practica esta fórmula con un ejercicio breve relacionado.", "Start Related Drill": "Iniciar práctica relacionada",
  "Averages And Operations": "Promedios y operaciones", "Revenue And Profitability": "Ingresos y rentabilidad", "Cost And Breakeven": "Costes y equilibrio", "Percent And Growth": "Porcentajes y crecimiento", "Returns And Investment": "Retorno e inversión",
  "Mix, capacity, and operating efficiency math.": "Cálculos de mezcla, capacidad y eficiencia operativa.", "Revenue, profit, margin, and market share formulas.": "Fórmulas de ingresos, beneficio, margen y cuota de mercado.", "Cost structure and volume needed to break even.": "Estructura de costes y volumen de equilibrio.", "Percent change, compounding, and growth shortcuts.": "Cambio porcentual, capitalización y atajos de crecimiento.", "Return and payback calculations for investment decisions.": "Cálculos de retorno y recuperación de inversiones."
};

const fr = {
  Reference: "Référence", "Formula Library": "Bibliothèque de formules", "Start Formula Drill": "Exercice de formules",
  "Find consulting math formulas, examples, and direct links into related practice.": "Retrouvez des formules de conseil, des exemples et les exercices associés.",
  "Find a Formula": "Trouver une formule", "Showing {visible} of {total} local formulas.": "{visible} formules locales affichées sur {total}.",
  "Clear Filters": "Effacer les filtres", "Search formulas": "Rechercher", "Margin, breakeven, growth...": "Marge, seuil de rentabilité, croissance...", "Formula category": "Catégorie", "All formulas": "Toutes les formules",
  "Category: All formulas": "Catégorie : toutes", "Category: {category}": "Catégorie : {category}", "Search: Any keyword": "Recherche : tous les mots", "Search: {search}": "Recherche : {search}", formula: "formule", formulas: "formules",
  "No Results": "Aucun résultat", "No formulas match the current filters.": "Aucune formule ne correspond aux filtres.", "Clear the filters to return to all formulas, or start a drill if you already know what you want to practice.": "Effacez les filtres pour retrouver toutes les formules ou commencez un exercice.",
  "Reset Formula Filters": "Réinitialiser les filtres", "Start Drill": "Commencer", Formula: "Formule", "How to use it": "Mode d’emploi", Example: "Exemple", "Practice this formula with a short built-in drill using related question templates.": "Entraînez-vous avec un court exercice associé.", "Start Related Drill": "Exercice associé",
  "Averages And Operations": "Moyennes et opérations", "Revenue And Profitability": "Chiffre d’affaires et rentabilité", "Cost And Breakeven": "Coûts et seuil de rentabilité", "Percent And Growth": "Pourcentages et croissance", "Returns And Investment": "Rendement et investissement"
};

const de = {
  Reference: "Nachschlagewerk", "Formula Library": "Formelsammlung", "Start Formula Drill": "Formeln üben", "Find consulting math formulas, examples, and direct links into related practice.": "Consulting-Formeln, Beispiele und passende Übungen.",
  "Find a Formula": "Formel finden", "Showing {visible} of {total} local formulas.": "{visible} von {total} lokalen Formeln.", "Clear Filters": "Filter löschen", "Search formulas": "Formeln suchen", "Margin, breakeven, growth...": "Marge, Break-even, Wachstum...", "Formula category": "Formelkategorie", "All formulas": "Alle Formeln", "Category: All formulas": "Kategorie: alle", "Category: {category}": "Kategorie: {category}", "Search: Any keyword": "Suche: beliebig", "Search: {search}": "Suche: {search}", formula: "Formel", formulas: "Formeln",
  "No Results": "Keine Ergebnisse", "No formulas match the current filters.": "Keine Formel entspricht den Filtern.", "Clear the filters to return to all formulas, or start a drill if you already know what you want to practice.": "Filter löschen oder direkt eine Übung starten.", "Reset Formula Filters": "Filter zurücksetzen", "Start Drill": "Übung starten", Formula: "Formel", "How to use it": "Anwendung", Example: "Beispiel", "Practice this formula with a short built-in drill using related question templates.": "Diese Formel mit einer kurzen passenden Übung trainieren.", "Start Related Drill": "Passende Übung starten",
  "Averages And Operations": "Durchschnitte und Operationen", "Revenue And Profitability": "Umsatz und Rentabilität", "Cost And Breakeven": "Kosten und Break-even", "Percent And Growth": "Prozent und Wachstum", "Returns And Investment": "Rendite und Investition"
};

const pt = {
  Reference: "Referência", "Formula Library": "Biblioteca de fórmulas", "Start Formula Drill": "Praticar fórmulas", "Find consulting math formulas, examples, and direct links into related practice.": "Consulte fórmulas de consultoria, exemplos e exercícios relacionados.",
  "Find a Formula": "Encontrar uma fórmula", "Showing {visible} of {total} local formulas.": "Exibindo {visible} de {total} fórmulas locais.", "Clear Filters": "Limpar filtros", "Search formulas": "Pesquisar fórmulas", "Margin, breakeven, growth...": "Margem, equilíbrio, crescimento...", "Formula category": "Categoria", "All formulas": "Todas as fórmulas", "Category: All formulas": "Categoria: todas", "Category: {category}": "Categoria: {category}", "Search: Any keyword": "Busca: qualquer termo", "Search: {search}": "Busca: {search}", formula: "fórmula", formulas: "fórmulas",
  "No Results": "Sem resultados", "No formulas match the current filters.": "Nenhuma fórmula corresponde aos filtros.", "Clear the filters to return to all formulas, or start a drill if you already know what you want to practice.": "Limpe os filtros ou inicie um exercício.", "Reset Formula Filters": "Redefinir filtros", "Start Drill": "Iniciar exercício", Formula: "Fórmula", "How to use it": "Como usar", Example: "Exemplo", "Practice this formula with a short built-in drill using related question templates.": "Pratique esta fórmula com um exercício curto relacionado.", "Start Related Drill": "Iniciar exercício relacionado",
  "Averages And Operations": "Médias e operações", "Revenue And Profitability": "Receita e rentabilidade", "Cost And Breakeven": "Custos e equilíbrio", "Percent And Growth": "Percentual e crescimento", "Returns And Investment": "Retorno e investimento"
};

const zhHans = {
  Reference: "参考", "Formula Library": "公式库", "Start Formula Drill": "开始公式练习", "Find consulting math formulas, examples, and direct links into related practice.": "查找咨询数学公式、示例和相关练习。", "Find a Formula": "查找公式", "Showing {visible} of {total} local formulas.": "显示 {total} 个本地公式中的 {visible} 个。", "Clear Filters": "清除筛选", "Search formulas": "搜索公式", "Margin, breakeven, growth...": "利润率、盈亏平衡、增长…", "Formula category": "公式类别", "All formulas": "所有公式", "Category: All formulas": "类别：全部", "Category: {category}": "类别：{category}", "Search: Any keyword": "搜索：任意关键词", "Search: {search}": "搜索：{search}", formula: "个公式", formulas: "个公式", "No Results": "无结果", "No formulas match the current filters.": "没有公式符合当前筛选条件。", "Clear the filters to return to all formulas, or start a drill if you already know what you want to practice.": "清除筛选以查看全部公式，或直接开始练习。", "Reset Formula Filters": "重置筛选", "Start Drill": "开始练习", Formula: "公式", "How to use it": "使用方法", Example: "示例", "Practice this formula with a short built-in drill using related question templates.": "通过相关的简短练习掌握此公式。", "Start Related Drill": "开始相关练习", "Averages And Operations": "平均值与运算", "Revenue And Profitability": "收入与盈利能力", "Cost And Breakeven": "成本与盈亏平衡", "Percent And Growth": "百分比与增长", "Returns And Investment": "回报与投资"
};

const zhHant = { ...zhHans, "Formula Library": "公式庫", "Start Formula Drill": "開始公式練習", "Find a Formula": "查找公式", "Clear Filters": "清除篩選", "Formula category": "公式類別", "All formulas": "所有公式", "No Results": "無結果", "Reset Formula Filters": "重設篩選", "Start Drill": "開始練習", "How to use it": "使用方法", "Start Related Drill": "開始相關練習", "Averages And Operations": "平均值與運算", "Revenue And Profitability": "營收與獲利能力", "Cost And Breakeven": "成本與損益平衡", "Percent And Growth": "百分比與成長", "Returns And Investment": "回報與投資" };

const ja = {
  Reference: "リファレンス", "Formula Library": "公式ライブラリ", "Start Formula Drill": "公式ドリルを開始", "Find consulting math formulas, examples, and direct links into related practice.": "コンサル数学の公式、例、関連練習を確認できます。", "Find a Formula": "公式を探す", "Showing {visible} of {total} local formulas.": "{total} 件中 {visible} 件を表示。", "Clear Filters": "フィルターを解除", "Search formulas": "公式を検索", "Margin, breakeven, growth...": "利益率、損益分岐点、成長…", "Formula category": "公式カテゴリ", "All formulas": "すべての公式", "Category: All formulas": "カテゴリ：すべて", "Category: {category}": "カテゴリ：{category}", "Search: Any keyword": "検索：すべて", "Search: {search}": "検索：{search}", formula: "件の公式", formulas: "件の公式", "No Results": "結果なし", "No formulas match the current filters.": "現在の条件に一致する公式はありません。", "Clear the filters to return to all formulas, or start a drill if you already know what you want to practice.": "条件を解除するか、ドリルを開始してください。", "Reset Formula Filters": "フィルターをリセット", "Start Drill": "ドリルを開始", Formula: "公式", "How to use it": "使い方", Example: "例", "Practice this formula with a short built-in drill using related question templates.": "関連する短いドリルでこの公式を練習します。", "Start Related Drill": "関連ドリルを開始", "Averages And Operations": "平均と演算", "Revenue And Profitability": "売上と収益性", "Cost And Breakeven": "コストと損益分岐点", "Percent And Growth": "割合と成長", "Returns And Investment": "収益と投資"
};

const ar = {
  Reference: "مرجع", "Formula Library": "مكتبة الصيغ", "Start Formula Drill": "بدء تمرين الصيغ", "Find consulting math formulas, examples, and direct links into related practice.": "اعثر على صيغ رياضيات الاستشارات وأمثلتها والتمارين المرتبطة بها.", "Find a Formula": "البحث عن صيغة", "Showing {visible} of {total} local formulas.": "عرض {visible} من أصل {total} صيغة محلية.", "Clear Filters": "مسح عوامل التصفية", "Search formulas": "البحث في الصيغ", "Margin, breakeven, growth...": "الهامش، التعادل، النمو...", "Formula category": "فئة الصيغة", "All formulas": "كل الصيغ", "Category: All formulas": "الفئة: الكل", "Category: {category}": "الفئة: {category}", "Search: Any keyword": "البحث: أي كلمة", "Search: {search}": "البحث: {search}", formula: "صيغة", formulas: "صيغ", "No Results": "لا توجد نتائج", "No formulas match the current filters.": "لا توجد صيغ تطابق عوامل التصفية الحالية.", "Clear the filters to return to all formulas, or start a drill if you already know what you want to practice.": "امسح عوامل التصفية أو ابدأ تمرينًا.", "Reset Formula Filters": "إعادة ضبط التصفية", "Start Drill": "بدء التمرين", Formula: "الصيغة", "How to use it": "طريقة الاستخدام", Example: "مثال", "Practice this formula with a short built-in drill using related question templates.": "تدرّب على هذه الصيغة بتمرين قصير مرتبط.", "Start Related Drill": "بدء تمرين مرتبط", "Averages And Operations": "المتوسطات والعمليات", "Revenue And Profitability": "الإيرادات والربحية", "Cost And Breakeven": "التكلفة والتعادل", "Percent And Growth": "النسب والنمو", "Returns And Investment": "العوائد والاستثمار"
};

const hi = {
  Reference: "संदर्भ", "Formula Library": "सूत्र पुस्तकालय", "Start Formula Drill": "सूत्र अभ्यास शुरू करें", "Find consulting math formulas, examples, and direct links into related practice.": "कंसल्टिंग गणित के सूत्र, उदाहरण और संबंधित अभ्यास खोजें।", "Find a Formula": "सूत्र खोजें", "Showing {visible} of {total} local formulas.": "{total} में से {visible} स्थानीय सूत्र दिख रहे हैं।", "Clear Filters": "फ़िल्टर हटाएँ", "Search formulas": "सूत्र खोजें", "Margin, breakeven, growth...": "मार्जिन, ब्रेक-ईवन, वृद्धि...", "Formula category": "सूत्र श्रेणी", "All formulas": "सभी सूत्र", "Category: All formulas": "श्रेणी: सभी", "Category: {category}": "श्रेणी: {category}", "Search: Any keyword": "खोज: कोई भी शब्द", "Search: {search}": "खोज: {search}", formula: "सूत्र", formulas: "सूत्र", "No Results": "कोई परिणाम नहीं", "No formulas match the current filters.": "वर्तमान फ़िल्टर से कोई सूत्र नहीं मिला।", "Clear the filters to return to all formulas, or start a drill if you already know what you want to practice.": "सभी सूत्र देखने के लिए फ़िल्टर हटाएँ या अभ्यास शुरू करें।", "Reset Formula Filters": "फ़िल्टर रीसेट करें", "Start Drill": "अभ्यास शुरू करें", Formula: "सूत्र", "How to use it": "उपयोग कैसे करें", Example: "उदाहरण", "Practice this formula with a short built-in drill using related question templates.": "संबंधित छोटे अभ्यास से इस सूत्र का अभ्यास करें।", "Start Related Drill": "संबंधित अभ्यास शुरू करें", "Averages And Operations": "औसत और संक्रियाएँ", "Revenue And Profitability": "राजस्व और लाभप्रदता", "Cost And Breakeven": "लागत और ब्रेक-ईवन", "Percent And Growth": "प्रतिशत और वृद्धि", "Returns And Investment": "रिटर्न और निवेश"
};

export const formulaMessages = { es, fr, de, pt, "zh-Hans": zhHans, "zh-Hant": zhHant, ja, ar, hi } satisfies PartialMessageCatalog;
