import type { PartialMessageCatalog } from "@/features/i18n/i18n";

const keys = {
  Appearance: ["Apariencia", "Apparence", "Erscheinungsbild", "Aparência", "外观", "外觀", "外観", "المظهر", "दिखावट"],
  Dark: ["Oscuro", "Sombre", "Dunkel", "Escuro", "深色", "深色", "ダーク", "داكن", "गहरा"],
  Light: ["Claro", "Clair", "Hell", "Claro", "浅色", "淺色", "ライト", "فاتح", "हल्का"],
  System: ["Sistema", "Système", "System", "Sistema", "系统", "系統", "システム", "النظام", "सिस्टम"],
  Theme: ["Tema", "Thème", "Design", "Tema", "主题", "主題", "テーマ", "السمة", "थीम"],
  "Local App Settings": ["Ajustes de la aplicación", "Paramètres locaux", "Lokale App-Einstellungen", "Configurações locais", "本地应用设置", "本機應用程式設定", "ローカル設定", "إعدادات التطبيق المحلي", "स्थानीय ऐप सेटिंग्स"],
  "Open Drill Setup": ["Abrir configuración", "Ouvrir les réglages", "Übung konfigurieren", "Abrir configuração", "打开练习设置", "開啟練習設定", "ドリル設定を開く", "فتح إعداد التمرين", "अभ्यास सेटअप खोलें"],
  Preferences: ["Preferencias", "Préférences", "Einstellungen", "Preferências", "偏好设置", "偏好設定", "環境設定", "التفضيلات", "प्राथमिकताएँ"],
  "Saved Drill Defaults": ["Valores predeterminados guardados", "Réglages d’exercice enregistrés", "Gespeicherte Übungsstandards", "Padrões salvos", "已保存的练习默认值", "已儲存的練習預設值", "保存済みドリル設定", "إعدادات التمرين المحفوظة", "सहेजी गई अभ्यास डिफ़ॉल्ट"],
  "Drill defaults": ["Valores predeterminados", "Réglages d’exercice", "Übungsstandards", "Padrões de exercício", "练习默认值", "練習預設值", "ドリル既定値", "إعدادات التمرين", "अभ्यास डिफ़ॉल्ट"],
  Questions: ["Preguntas", "Questions", "Fragen", "Questões", "题目", "題目", "問題", "الأسئلة", "प्रश्न"], Difficulty: ["Dificultad", "Difficulté", "Schwierigkeit", "Dificuldade", "难度", "難度", "難易度", "الصعوبة", "कठिनाई"], Timing: ["Tiempo", "Chronométrage", "Zeit", "Tempo", "计时", "計時", "時間設定", "التوقيت", "समय"], Feedback: ["Comentarios", "Retour", "Feedback", "Feedback", "反馈", "回饋", "フィードバック", "التغذية الراجعة", "फ़ीडबैक"],
  "Local Data": ["Datos locales", "Données locales", "Lokale Daten", "Dados locais", "本地数据", "本機資料", "ローカルデータ", "البيانات المحلية", "स्थानीय डेटा"],
  "Export or replace local progress": ["Exportar o reemplazar progreso", "Exporter ou remplacer la progression", "Fortschritt exportieren oder ersetzen", "Exportar ou substituir progresso", "导出或替换本地进度", "匯出或取代本機進度", "進捗をエクスポートまたは置換", "تصدير التقدم المحلي أو استبداله", "स्थानीय प्रगति निर्यात या बदलें"],
  "Export Local Progress": ["Exportar progreso", "Exporter la progression", "Fortschritt exportieren", "Exportar progresso", "导出本地进度", "匯出本機進度", "ローカル進捗をエクスポート", "تصدير التقدم المحلي", "स्थानीय प्रगति निर्यात करें"],
  "Exporting...": ["Exportando...", "Exportation…", "Export wird erstellt…", "Exportando...", "正在导出…", "正在匯出…", "エクスポート中…", "جارٍ التصدير...", "निर्यात हो रहा है..."],
  "Import Local Progress": ["Importar progreso", "Importer la progression", "Fortschritt importieren", "Importar progresso", "导入本地进度", "匯入本機進度", "ローカル進捗をインポート", "استيراد التقدم المحلي", "स्थानीय प्रगति आयात करें"],
  "Import And Replace": ["Importar y reemplazar", "Importer et remplacer", "Importieren und ersetzen", "Importar e substituir", "导入并替换", "匯入並取代", "インポートして置換", "استيراد واستبدال", "आयात करके बदलें"],
  "Importing...": ["Importando...", "Importation…", "Import läuft…", "Importando...", "正在导入…", "正在匯入…", "インポート中…", "جارٍ الاستيراد...", "आयात हो रहा है..."],
  "Content Packs": ["Paquetes de contenido", "Packs de contenu", "Inhaltspakete", "Pacotes de conteúdo", "内容包", "內容包", "コンテンツパック", "حزم المحتوى", "कंटेंट पैक"],
  "Manage optional local question packs": ["Gestionar paquetes locales opcionales", "Gérer les packs locaux facultatifs", "Optionale lokale Fragenpakete verwalten", "Gerenciar pacotes locais opcionais", "管理可选本地题库", "管理選用本機題庫", "任意のローカル問題パックを管理", "إدارة حزم الأسئلة المحلية الاختيارية", "वैकल्पिक स्थानीय प्रश्न पैक प्रबंधित करें"],
  Offline: ["Sin conexión", "Hors ligne", "Offline", "Offline", "离线", "離線", "オフライン", "دون اتصال", "ऑफ़लाइन"],
  "Understand local and offline use": ["Entender el uso local y sin conexión", "Comprendre l’utilisation locale et hors ligne", "Lokale und Offline-Nutzung", "Entenda o uso local e offline", "了解本地与离线使用", "瞭解本機與離線使用", "ローカル・オフライン利用について", "فهم الاستخدام المحلي ودون اتصال", "स्थानीय और ऑफ़लाइन उपयोग समझें"],
  Browser: ["Navegador", "Navigateur", "Browser", "Navegador", "浏览器", "瀏覽器", "ブラウザー", "المتصفح", "ब्राउज़र"], "Practice Content": ["Contenido de práctica", "Contenu d’entraînement", "Übungsinhalte", "Conteúdo de prática", "练习内容", "練習內容", "練習コンテンツ", "محتوى التدريب", "अभ्यास सामग्री"], "Progress Sync": ["Sincronización", "Synchronisation", "Fortschrittssynchronisierung", "Sincronização", "进度同步", "進度同步", "進捗同期", "مزامنة التقدم", "प्रगति सिंक"], None: ["Ninguna", "Aucune", "Keine", "Nenhuma", "无", "無", "なし", "لا يوجد", "कोई नहीं"],
  "Keep Practicing": ["Sigue practicando", "Continuez à vous entraîner", "Weiter üben", "Continue praticando", "继续练习", "繼續練習", "練習を続ける", "واصل التدريب", "अभ्यास जारी रखें"], "Open Once First": ["Ábrelo una vez", "Ouvrez d’abord une fois", "Einmal online öffnen", "Abra uma vez primeiro", "先在线打开一次", "先在線開啟一次", "最初に一度開く", "افتحه مرة أولاً", "पहले एक बार खोलें"], "Saved Here": ["Guardado aquí", "Enregistré ici", "Hier gespeichert", "Salvo aqui", "保存在此处", "儲存在此處", "ここに保存", "محفوظ هنا", "यहाँ सहेजा गया"],
  Reset: ["Restablecer", "Réinitialiser", "Zurücksetzen", "Redefinir", "重置", "重設", "リセット", "إعادة الضبط", "रीसेट"], "Reset local data": ["Restablecer datos locales", "Réinitialiser les données locales", "Lokale Daten zurücksetzen", "Redefinir dados locais", "重置本地数据", "重設本機資料", "ローカルデータをリセット", "إعادة ضبط البيانات المحلية", "स्थानीय डेटा रीसेट करें"], "Reset Local Data": ["Restablecer datos locales", "Réinitialiser les données", "Lokale Daten zurücksetzen", "Redefinir dados locais", "重置本地数据", "重設本機資料", "ローカルデータをリセット", "إعادة ضبط البيانات المحلية", "स्थानीय डेटा रीसेट करें"],
  "Reset only affects this device.": ["El restablecimiento solo afecta a este dispositivo.", "La réinitialisation ne concerne que cet appareil.", "Das Zurücksetzen betrifft nur dieses Gerät.", "A redefinição afeta apenas este dispositivo.", "重置仅影响此设备。", "重設只會影響此裝置。", "リセットはこの端末にのみ影響します。", "تؤثر إعادة الضبط في هذا الجهاز فقط.", "रीसेट केवल इस डिवाइस को प्रभावित करता है।"],
  Export: ["Exportación", "Export", "Export", "Exportação", "导出", "匯出", "エクスポート", "تصدير", "निर्यात"], Import: ["Importación", "Import", "Import", "Importação", "导入", "匯入", "インポート", "استيراد", "आयात"], "Local data": ["Datos locales", "Données locales", "Lokale Daten", "Dados locais", "本地数据", "本機資料", "ローカルデータ", "البيانات المحلية", "स्थानीय डेटा"], Sessions: ["Sesiones", "Sessions", "Sitzungen", "Sessões", "练习", "練習", "セッション", "الجلسات", "सत्र"], Responses: ["Respuestas", "Réponses", "Antworten", "Respostas", "回答", "回答", "回答", "الإجابات", "उत्तर"], Benchmarks: ["Evaluaciones", "Évaluations", "Benchmarks", "Avaliações", "基准测试", "基準測試", "ベンチマーク", "الاختبارات المعيارية", "बेंचमार्क"], Exhibits: ["Gráficos", "Graphiques", "Diagramme", "Gráficos", "图表", "圖表", "図表", "الرسوم البيانية", "चार्ट"], "Case Practice": ["Práctica de casos", "Études de cas", "Fallstudien", "Prática de casos", "案例练习", "案例練習", "ケース練習", "تدريب الحالات", "केस अभ्यास"],
  "Review saved defaults and manage data stored in this browser. Drill setup changes affect one launch unless you explicitly save them as defaults.": ["Revisa los valores predeterminados y gestiona los datos guardados en este navegador. Los cambios de configuración solo afectan a una sesión, salvo que los guardes como predeterminados.", "Consultez les réglages enregistrés et gérez les données de ce navigateur. Les modifications ne concernent qu’une session, sauf si vous les enregistrez par défaut.", "Prüfen Sie gespeicherte Standards und verwalten Sie die Daten in diesem Browser. Änderungen gelten nur für einen Start, sofern Sie sie nicht als Standard speichern.", "Revise os padrões salvos e gerencie os dados deste navegador. As alterações valem para uma sessão, a menos que sejam salvas como padrão.", "查看已保存的默认设置并管理此浏览器中的数据。练习设置更改仅影响一次启动，除非明确保存为默认值。", "查看已儲存的預設設定並管理此瀏覽器中的資料。練習設定變更只影響一次啟動，除非明確儲存為預設值。", "保存済みの既定値とブラウザー内のデータを管理します。設定変更は、既定値として保存しない限り今回の開始にのみ適用されます。", "راجع الإعدادات الافتراضية المحفوظة وأدر البيانات المخزنة في هذا المتصفح. تنطبق تغييرات الإعداد على تشغيل واحد ما لم تحفظها كإعدادات افتراضية.", "सहेजी गई डिफ़ॉल्ट सेटिंग देखें और इस ब्राउज़र में संग्रहीत डेटा प्रबंधित करें। सेटअप बदलाव केवल एक सत्र पर लागू होते हैं, जब तक आप उन्हें डिफ़ॉल्ट के रूप में न सहेजें।"],
  "Loading saved drill defaults...": ["Cargando valores predeterminados guardados...", "Chargement des réglages d’exercice enregistrés…", "Gespeicherte Übungsstandards werden geladen…", "Carregando padrões de exercício salvos...", "正在加载已保存的练习默认值…", "正在載入已儲存的練習預設值…", "保存済みのドリル既定値を読み込み中…", "جارٍ تحميل إعدادات التمرين الافتراضية المحفوظة...", "सहेजी गई अभ्यास डिफ़ॉल्ट लोड हो रही हैं..."],
  "Built-in defaults initialize Drill Selection. Setup changes affect one launch unless you choose Save as my defaults.": ["Los valores integrados inicializan la selección. Los cambios solo afectan a una sesión, salvo que elijas Guardar como predeterminados.", "Les réglages intégrés initialisent la sélection. Les modifications ne concernent qu’une session, sauf si vous choisissez Enregistrer comme réglages par défaut.", "Die integrierten Standards initialisieren die Übungsauswahl. Änderungen gelten nur für einen Start, sofern Sie nicht Als Standard speichern wählen.", "Os padrões integrados iniciam a seleção. As alterações valem para uma sessão, a menos que você escolha Salvar como meus padrões.", "内置默认值用于初始化练习选择。设置更改仅影响一次启动，除非选择“保存为我的默认值”。", "內建預設值用於初始化練習選擇。設定變更只影響一次啟動，除非選擇「儲存為我的預設值」。", "組み込みの既定値でドリル選択を初期化します。変更は「既定値として保存」を選ばない限り今回のみ有効です。", "تُهيئ الإعدادات المضمنة اختيار التمرين. تنطبق التغييرات على تشغيل واحد ما لم تختر الحفظ كإعداداتي الافتراضية.", "अंतर्निहित डिफ़ॉल्ट अभ्यास चयन को शुरू करते हैं। बदलाव केवल एक सत्र पर लागू होते हैं, जब तक आप मेरी डिफ़ॉल्ट के रूप में सहेजें न चुनें।"],
  "These saved defaults initialize Drill Selection. Changing a drill affects only that launch until you choose Save as my defaults.": ["Estos valores guardados inicializan la selección. Los cambios solo afectan a esa sesión hasta que elijas Guardar como predeterminados.", "Ces réglages enregistrés initialisent la sélection. Les modifications ne concernent que cette session jusqu’à ce que vous choisissiez Enregistrer comme réglages par défaut.", "Diese gespeicherten Standards initialisieren die Übungsauswahl. Änderungen gelten nur für diesen Start, bis Sie Als Standard speichern wählen.", "Esses padrões salvos iniciam a seleção. As alterações afetam apenas essa sessão até você escolher Salvar como meus padrões.", "这些已保存的默认值用于初始化练习选择。更改仅影响本次启动，直到选择“保存为我的默认值”。", "這些已儲存的預設值用於初始化練習選擇。變更只影響本次啟動，直到選擇「儲存為我的預設值」。", "保存済みの既定値でドリル選択を初期化します。変更は「既定値として保存」を選ぶまで今回のみ有効です。", "تُهيئ هذه الإعدادات المحفوظة اختيار التمرين. تؤثر التغييرات في هذا التشغيل فقط حتى تختار الحفظ كإعداداتي الافتراضية.", "ये सहेजी गई डिफ़ॉल्ट अभ्यास चयन को शुरू करती हैं। बदलाव केवल इस सत्र पर लागू होते हैं, जब तक आप मेरी डिफ़ॉल्ट के रूप में सहेजें न चुनें।"],
  "No progress is sent to a server. Clearing browser storage or using reset removes local practice history.": ["No se envía progreso a ningún servidor. Borrar el almacenamiento del navegador o restablecer elimina el historial local.", "Aucune progression n’est envoyée à un serveur. Effacer le stockage du navigateur ou réinitialiser supprime l’historique local.", "Es wird kein Fortschritt an einen Server gesendet. Das Löschen des Browserspeichers oder Zurücksetzen entfernt den lokalen Verlauf.", "Nenhum progresso é enviado a um servidor. Limpar o armazenamento do navegador ou redefinir remove o histórico local.", "进度不会发送到服务器。清除浏览器存储或使用重置会删除本地练习历史。", "進度不會傳送到伺服器。清除瀏覽器儲存空間或使用重設會刪除本機練習記錄。", "進捗はサーバーに送信されません。ブラウザーの保存領域を消去するかリセットすると、ローカル履歴が削除されます。", "لا يُرسل أي تقدم إلى خادم. يؤدي مسح تخزين المتصفح أو استخدام إعادة الضبط إلى حذف سجل التدريب المحلي.", "कोई प्रगति सर्वर पर नहीं भेजी जाती। ब्राउज़र स्टोरेज साफ़ करने या रीसेट करने से स्थानीय अभ्यास इतिहास हट जाता है।"],
  "I understand this replaces local progress on this device.": ["Entiendo que esto reemplaza el progreso local de este dispositivo.", "Je comprends que cette action remplace la progression locale sur cet appareil.", "Ich verstehe, dass dadurch der lokale Fortschritt auf diesem Gerät ersetzt wird.", "Entendo que isso substitui o progresso local neste dispositivo.", "我了解此操作会替换此设备上的本地进度。", "我瞭解此操作會取代此裝置上的本機進度。", "この操作でこの端末のローカル進捗が置き換わることを理解しました。", "أفهم أن هذا سيستبدل التقدم المحلي على هذا الجهاز.", "मैं समझता/समझती हूँ कि इससे इस डिवाइस की स्थानीय प्रगति बदल जाएगी।"],
  "This clears saved drill defaults, drill history, benchmark results, market sizing attempts, and exhibit attempts from this browser.": ["Esto borra del navegador los valores de práctica, el historial, los resultados de evaluaciones y los intentos de mercado y gráficos.", "Cette action efface de ce navigateur les réglages, l’historique, les résultats d’évaluation et les tentatives de marché et de graphiques.", "Dadurch werden Übungsstandards, Verlauf, Benchmark-Ergebnisse sowie Marktgrößen- und Diagrammversuche aus diesem Browser gelöscht.", "Isso apaga deste navegador os padrões, o histórico, os resultados de avaliações e as tentativas de mercado e gráficos.", "这会从此浏览器中清除已保存的练习默认值、练习历史、基准测试结果、市场规模和图表尝试。", "這會從此瀏覽器中清除已儲存的練習預設值、練習記錄、基準測試結果、市場規模和圖表作答。", "このブラウザーから、ドリル既定値、履歴、ベンチマーク結果、市場規模推定と図表の回答を消去します。", "يؤدي هذا إلى مسح إعدادات التمرين وسجله ونتائج الاختبارات ومحاولات تقدير السوق والرسوم من هذا المتصفح.", "यह इस ब्राउज़र से अभ्यास डिफ़ॉल्ट, इतिहास, बेंचमार्क परिणाम, मार्केट साइज़िंग और चार्ट प्रयास साफ़ कर देता है।"],
  "The app will return to default preferences after reset. Built-in content and installed question packs stay available.": ["La aplicación volverá a las preferencias predeterminadas. El contenido integrado y los paquetes instalados seguirán disponibles.", "L’application reviendra aux préférences par défaut. Le contenu intégré et les packs installés resteront disponibles.", "Die App kehrt zu den Standardeinstellungen zurück. Integrierte Inhalte und installierte Fragenpakete bleiben verfügbar.", "O app voltará às preferências padrão. O conteúdo integrado e os pacotes instalados continuarão disponíveis.", "重置后应用会恢复默认偏好设置。内置内容和已安装题库仍然可用。", "重設後應用程式會恢復預設偏好設定。內建內容和已安裝題庫仍然可用。", "リセット後は既定の設定に戻ります。組み込みコンテンツとインストール済みパックは引き続き利用できます。", "سيعود التطبيق إلى التفضيلات الافتراضية بعد إعادة الضبط. سيبقى المحتوى المضمن وحزم الأسئلة المثبتة متاحًا.", "रीसेट के बाद ऐप डिफ़ॉल्ट प्राथमिकताओं पर लौटेगा। अंतर्निहित सामग्री और इंस्टॉल किए गए प्रश्न पैक उपलब्ध रहेंगे।"],
  "I understand this clears local practice data on this device.": ["Entiendo que esto borra los datos de práctica locales de este dispositivo.", "Je comprends que cette action efface les données d’entraînement locales sur cet appareil.", "Ich verstehe, dass dadurch lokale Übungsdaten auf diesem Gerät gelöscht werden.", "Entendo que isso apaga os dados de prática locais neste dispositivo.", "我了解此操作会清除此设备上的本地练习数据。", "我瞭解此操作會清除此裝置上的本機練習資料。", "この操作でこの端末のローカル練習データが消去されることを理解しました。", "أفهم أن هذا سيمسح بيانات التدريب المحلية على هذا الجهاز.", "मैं समझता/समझती हूँ कि इससे इस डिवाइस का स्थानीय अभ्यास डेटा साफ़ हो जाएगा।"],
  "Skill Scores": ["Puntuaciones por habilidad", "Scores par compétence", "Fähigkeitswerte", "Pontuações por habilidade", "技能得分", "技能分數", "スキルスコア", "درجات المهارات", "कौशल स्कोर"]
} as const;

const localeOrder = ["es", "fr", "de", "pt", "zh-Hans", "zh-Hant", "ja", "ar", "hi"] as const;
export const settingsMessages = Object.fromEntries(localeOrder.map((locale, index) => [locale, Object.fromEntries(Object.entries(keys).map(([key, values]) => [key, values[index]]))])) satisfies PartialMessageCatalog;
